spring:
  application:
    name: rbpo-servak
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-jwt:
    expiration: ${ACCESS_JWT_EXPIRATION}  # например, 3600000 (1 час)
  refresh-jwt:
    expiration: ${REFRESH_JWT_EXPIRATION} # например, 2592000000 (30 дней)

server:
  http2:
    enabled: true
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}