spring:
  application:
    name: rbpo-servak
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-jwt:
    expiration: ${ACCESS_JWT_EXPIRATION}
  refresh-jwt:
    expiration: ${REFRESH_JWT_EXPIRATION}

security:
  rsa:
    private-key: ${PRIVATE_KEY}
    public-key: ${PUBLIC_KEY}

server:
  http2:
    enabled: true
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}