spring:
  application:
    name: servak
  datasource:
    url: jdbc:postgresql://localhost:5440/rbpo_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}

server:
  http2:
    enabled: true
  ssl:
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASS}
    key-alias: ${KEY_ALIAS}